# Generated by Django 3.2 on 2023-10-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq Ismi")),
                ('telegram_id', models.BigIntegerField(null=True, unique=True, verbose_name='Telegram ID')),
                ('count', models.BigIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=250, null=True, unique=True)),
                ('invoice', models.TextField()),
            ],
            options={
                'verbose_name': 'Nakladnoy',
                'verbose_name_plural': 'Nakladnoy',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xizmat Nomi')),
                ('price', models.BigIntegerField(null=True, verbose_name='Xizmat Narxi')),
                ('description', models.TextField(verbose_name='Xizmat Haqida')),
            ],
            options={
                'verbose_name': 'Xizmatlar',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=250, null=True, verbose_name='Mijoz Telefon raqami')),
                ('delivered', models.BooleanField(null=True, verbose_name='Yetkazib berildi')),
                ('is_completed', models.BooleanField(verbose_name='Tugatildimi')),
                ('price', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Umumiy Narx')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service', verbose_name='Xizmat turi')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_orders', to='base.customuser', verbose_name='Yetkazib beruvchi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='base.customuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
