# Generated by Django 3.2 on 2023-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
