# Generated by Django 4.2.5 on 2023-10-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Xizmatlar', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="To'liq Ismi"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(verbose_name='Tugatildimi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(null=True, verbose_name='Mijoz Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Umumiy Narx'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service', verbose_name='Xizmat turi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Xizmat Haqida'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Xizmat Nomi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.BigIntegerField(null=True, verbose_name='Xizmat Narxi'),
        ),
    ]
