# Generated by Django 4.2.5 on 2023-10-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-count'], 'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(null=True, verbose_name='Yetkazib berildi'),
        ),
    ]
