# Generated by Django 4.2.5 on 2023-10-06 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_supplier_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_orders', to='base.customuser', verbose_name='Yetkazib beruvchi'),
        ),
    ]
