# Generated by Django 4.2.5 on 2023-10-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(null=True, upload_to='media/', verbose_name='Naklodnoy'),
        ),
    ]
