# Generated by Django 4.2.5 on 2023-10-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_order_invoice_remove_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
    ]
