# Generated by Django 4.2.5 on 2023-10-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
