# Generated by Django 4.2.5 on 2023-10-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_invoice_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='file_id',
            new_name='invoice',
        ),
    ]
